### ISSUE TITLE
Can I use this pulgin for dynamic forms?

### ISSUE THREAD

**Issue by vaibhav-jain** [ReactiveRaven/jqBootstrapValidation#175]
I have a form on which I want to perform validation but this form can be changed dynamically.
For example: Form for creating `Authors` and more then one `Books` can be added dynamically. Now I want to perform validation for this form. Is it possible with this plugin??? And on some fields I have some function call via `onblur`

**Comment by vaibhav-jain** [comment]
I am facing this [issue](http://www.stackoverflow.com/questions/27989743/jquery-form-validation-with-django-dynamic-formset) Please have a look

**Comment by eridanaeon** [comment]
Yes you can but you need to make some modification on the code, at method.init :
```javascript
methods: {
	init: function (options) {
		var settings = $.extend(true, {}, defaults);
		settings.options = $.extend(true, settings.options, options);
		var $siblingElements = this;

		var uniqueForms = $.unique(
			$siblingElements.map(function () {
				return $(this).parents("form")[0];
			}).toArray()
		);

		//mod by acs
		$(uniqueForms).unbind("submit");
		
		$(uniqueForms).bind("submit", function (e) {
			var $form = $(this);
			var warningsFound = 0;
.
.
.
.
```

Reason for this is to prevent multiple validations, let's say blur event happened thrice, that would mean three validation actions leading to three calls to submitSuccess / submitError blocks. 

Similar to what you're doing.... or close enough... validation selector is based on what the user chose, here's how it used it:

```html
<select 
	id="tmf-001" class="span4" ng-model="Type" 
        ng-change="modalForm.initValidation();"
	required="" data-validation-required-message="select from list"
>
	<option value="">Please select</option>
	<option value="1">1</option>
	<option value="2">2</option>
</select>
```

```javascript
this.initValidation = function(){
	var selector1 = '#tmf-001, #tmf-002, #tmf-003, #tmf-004';
	var selector2 = '#tmf-001, #tmf-002, #tmf-004';
	var selector3 = '#tmf-001';
	var selector = '';
	
   
	//validation done based on action
	if(this.action === '1'){
        .       some code for selector
        .
        .
        .
	
	if(this.validator.jqBootstrapValidation){
		this.validator.jqBootstrapValidation('destroy'); //remove previous validations
		delete this.validator.jqBootstrapValidation;
	}
	
	this.validator = $(selector).not('[type=submit]').jqBootstrapValidation({
		preventSubmit: true,
		submitError: function ($form, event) {
			console.log('validation fail');
			//do whatever
		},
		submitSuccess: function ($form, event) {
			console.log('validation success, action : ', directive.action);
			//do whatever
		}
	});
};
```

You might also want to check this issue,https://github.com/ReactiveRaven/jqBootstrapValidation/issues/157, regarding calls to *'destroy'*

**Comment by vaibhav-jain** [comment]
Thanks....
