### ISSUE TITLE
Support for modal

### ISSUE THREAD

**Issue by Mte90** [ReactiveRaven/jqBootstrapValidation#22]
on my app i have modded this plugin for support the modal.
https://github.com/Mte90/Simple-Invoice-Manager/commit/e45a89e0cdcce1e399e0324282175de83058b256
This commit conatian the version modded :-)

the problem on modal that the button are out of the form.
i have added a data tag on parent of the button that contain the id of the form, a new option that contain the event :

``` javascript
jQuery(document).on(
    'change',
    'input,select,textarea :not([type=submit])',
    function() {
        jQuery(this).jqBootstrapValidation();
    }
);
jQuery(document).on(
    'click',
    '.btn-primary',
    function(e) {
        jQuery('input,select,textarea').jqBootstrapValidation();
        jQuery(this).jqBootstrapValidation('init',{event:e});
    }
);
```

With my hack for execute the check on click and the prevent of submit need to use the init method.

**Comment by prabhjot6785** [comment]
This script not working in bootstrap modal.
