### ISSUE TITLE
How do I stop form elements that are not visible from being validated?

### ISSUE THREAD

**Issue by benscammell** [ReactiveRaven/jqBootstrapValidation#35]
I have a form with two parts, each inside a div.

I show and hide these divs based on a drop down.

How do I stop the form items inside the hidden div from being validated?

Or is there a better way for me to create this dynamic form?

Thanks,

Ben

**Comment by adm0442** [comment]
Hi Team  
I have been struggling with this for a while  
In a nutshell All i have been trying to achieve is to  validate a select field with jqBootstrapValidation.

This is my html code below 
  

<form id="contactForm" name="sentMessage" novalidate="novalidate">
<div class="form-group">
                  <select class="form-control" id="choice" name="choice" required="required"  data-validation-required-message="Please Choose.">
                    <option value="" disabled="disabled"></option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                 </select>
                 <p class="help-block text-danger"></p>
                </div>


 <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit">Send Message</button>


 </form>



-- 

And this is the start of my javascript 
$(function() {

  $("#contactForm input,#contactForm textarea,#contactForm select").jqBootstrapValidation({
    preventSubmit: true,
    submitError: function($form, event, errors) {
      // additional error messages or events
    },


But i cant  get the  select fields to  validate  
Please help with this

**Comment by adm0442** [comment]
Hi @ReactiveRaven @cleentfaar 
I am sure this is going to be very very simple for a Guru like you
In a nutshell All i have been trying to achieve is to  validate a select field with jqBootstrapValidation.
This is my html code below 

`<div class="form-group">
                  <select class="form-control" id="choice" name="choice" required="required"  data-validation-required-message="Please Choose.">
                    <option value="" disabled="disabled"></option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                 </select>
                 <p class="help-block text-danger"></p>
                </div>`

Here is my javascript

`$(function() {

  $("#contactForm input,#contactForm textarea,#contactForm select").jqBootstrapValidation({
    preventSubmit: true,
    submitError: function($form, event, errors) {
      // additional error messages or events
    },`

So far i have not been able to get the select fields to validate as input and textarea 
Any help will be appreciated here 

Thanks
