### ISSUE TITLE
Unable to override validationRequiredMessage

### ISSUE THREAD

**Issue by oliversalzburg** [ReactiveRaven/jqBootstrapValidation#53]
Even if I set data-validation-required-message on my input box, I still get the default error message.

The value is read just fine using `$this.data("validationRequiredMessage")`, yet, the value isn't used. I confirmed this at https://github.com/ReactiveRaven/jqBootstrapValidation/blob/1.3.6/jqBootstrapValidation.js#L164

While hunting for the source of this, I noticed something weird at https://github.com/ReactiveRaven/jqBootstrapValidation/blob/1.3.6/jqBootstrapValidation.js#L288 It looked to me like `hasOverrideMessage` is **always** `true` because the messages were set earlier. A simple `alert(hasOverrideMessage)` confirms this.

So, I'm somewhat confused about what's going on.

**Comment by GuiDeto** [comment]
<form method="post" class="form-horizontal" novalidate>

**Comment by FFDomm** [comment]
Hello all.

I have validated my textbox like **oliversalzburg ** and the image "Fill in this field"

The only problem is that is in SPANISH! I need it to be in english.

can anyone help me??

My html is like this <HTML lang="en">.
I have no idea how to make it appear in english.

**Comment by FFDomm** [comment]
I finally got it!

all i did was clear the custom validity property on each textbox

placeholder="Signum" required **oninput="setCustomValidity('')" **oninvalid="this.setCustomValidity('Please enter Signum')"


:)
